export default function useGeneratedCards() {
  const Cards = [
    {
      "Name": "Introduction",
      "id": "505dc8c39ed34f48ad448e8146dcb60e",
      "Molecule": "Premier jour au japon",
      "Person": "e",
      "Status": "To Be checked",
      "card_type": "dialogue_card",
      "character": "persoexplication",
      "condition": "Uniquement première partie",
      "question": "Hé bien! Te voilà à Tokyo pour une année de cours à l’étranger. Je suis [trucname] et je veillerais à ce que ce ton séjour ici se passe parfaitement !",
      "leftText": "Oh !",
      "onLeft": "",
      "rightText": "Euh ?",
      "onRight": "",
      "left_custom": "",
      "right_custom": "",
      "left_next_card": "36f2fddae5f4434da9bc76f0763a28c2",
      "right_next_card": "36f2fddae5f4434da9bc76f0763a28c2",
      "ordre": "",
      "difficulté": "",
      "Kanji": "",
      "background": "#ccc",
      "image": "https://cdn-icons-png.flaticon.com/512/9183/9183995.png",
      "itemId": ""
    },
    {
      "Name": "Introduction_tuto",
      "id": "36f2fddae5f4434da9bc76f0763a28c2",
      "Molecule": "Premier jour au japon",
      "Person": "e",
      "Status": "To Be checked",
      "card_type": "dialogue_card",
      "character": "persoexplication",
      "condition": "Uniquement première partie",
      "question": "Pour ce faire tu dois surveiller que ces jauges soient toujours pleines mais sans déborder ! Lors de ton année ces jauges varieront selon les choix que tu fais. Tiens essaie avec moi.",
      "leftText": "Acheter et manger un sandwich",
      "onLeft": "-5 A +10 H",
      "rightText": "Acheter un joli chapeau",
      "onRight": "-10 A +10 P + 10 B",
      "left_custom": "",
      "right_custom": "",
      "left_next_card": "703186931b994813ac8e89a5c2197fd3",
      "right_next_card": "703186931b994813ac8e89a5c2197fd3",
      "ordre": "",
      "difficulté": "",
      "Kanji": "",
      "background": "#ccc",
      "image": "https://cdn-icons-png.flaticon.com/512/9183/9183995.png",
      "itemId": ""
    },
    {
      "Name": "Introduction_tuto_2",
      "id": "703186931b994813ac8e89a5c2197fd3",
      "Molecule": "Premier jour au japon",
      "Person": "e",
      "Status": "To Be checked",
      "card_type": "dialogue_card",
      "character": "persoexplication",
      "condition": "Uniquement première partie",
      "question": "Parfait ! Je suis certain que tu te débrouilleras parfaitement. Je passerais te voir de temps en temps.",
      "leftText": "A très vite!",
      "onLeft":  { happy: [], sad: ['joker'] },
      "rightText": "ok bye",
      "onRight": { happy: ['knight'], sad: ['joker'] },
      "left_custom": "Tutoriel 1 passé",
      "right_custom": "Tutoriel 1 passé",
      "left_next_card": "3bc4abad722545aabcd9a01e30aaabcd",
      "right_next_card": "3bc4abad722545aabcd9a01e30aaabcd",
      "ordre": "",
      "difficulté": "",
      "Kanji": "",
      "background": "#ccc",
      "image": "https://cdn-icons-png.flaticon.com/512/9183/9183995.png",
      "itemId": ""
    },
    {
      "Name": "choix_transport",
      "id": "3bc4abad722545aabcd9a01e30aaabcd",
      "Molecule": "Premier jour au japon",
      "Person": "",
      "Status": "",
      "card_type": "multiple_answer_card",
      "character": "sans",
      "condition": "",
      "question": "",
      "leftText": "",
      "onLeft": "",
      "rightText": "",
      "onRight": "",
      "left_custom": "",
      "right_custom": "",
      "left_next_card": "",
      "right_next_card": "",
      "ordre": "",
      "difficulté": "",
      "Kanji": "marcher (足) voiture(車) train(電車)",
      "background": "#ccc",
      "image": "https://cdn-icons-png.flaticon.com/512/3267/3267450.png",
      "itemId": ""
    },
    {
      "Name": "choix_transport_taxi",
      "id": "1a1681d447ac4562a19d1b10d9ecf137",
      "Molecule": "Premier jour au japon",
      "Person": "e",
      "Status": "To Be checked",
      "card_type": "story_card",
      "character": "sans",
      "condition": "",
      "question": "C’était peut être cher mais tu es arrivé sans encombre. Le chauffeur était vachement bavard mais tu n’as pas compris un mot et tu t’es contenté de hocher la tête … Ah ! Il serait temps de prendre quelques cours.",
      "leftText": "",
      "onLeft": "",
      "rightText": "",
      "onRight": "-20 A + 5 B",
      "left_custom": "",
      "right_custom": "",
      "left_next_card": "0df94147ee8f4dfda5f631224e43e74d",
      "right_next_card": "0df94147ee8f4dfda5f631224e43e74d",
      "ordre": "",
      "difficulté": "",
      "Kanji": "",
      "background": "#ccc",
      "image": "https://cdn-icons-png.flaticon.com/512/3357/3357912.png",
      "itemId": ""
    },
    {
      "Name": "choix_transport_transport",
      "id": "d97ebf2a4a0f412dba7c2cfdbffff291",
      "Molecule": "Premier jour au japon",
      "Person": "e",
      "Status": "To Be checked",
      "card_type": "story_card",
      "character": "sans",
      "condition": "",
      "question": "Pfiou! S’orienter dans une ville étrangère c’est éprouvant. Tous ces kanjis inconnus te donnent mal à la tête. Tu parviens tout de même à monter dans le métro que tu cherchais pour rentrer.",
      "leftText": "non",
      "onLeft": "",
      "rightText": "j'achète mon billet",
      "onRight": "-5 A - 5 B",
      "left_custom": "",
      "right_custom": "",
      "left_next_card": "",
      "right_next_card": "",
      "ordre": "",
      "difficulté": "",
      "Kanji": "",
      "background": "#ccc",
      "image": "https://cdn-icons-png.flaticon.com/512/3313/3313514.png",
      "itemId": ""
    },
    {
      "Name": "choix_transport_marcher",
      "id": "2db19f997a904d848fd2fd36d77d5404",
      "Molecule": "Premier jour au japon",
      "Person": "e",
      "Status": "To Be checked",
      "card_type": "story_card",
      "character": "sans",
      "condition": "",
      "question": "Pfiou! S’orienter dans une ville étrangère c’est éprouvant. Tous ces kanjis inconnus ont eu raison de toi et te voilà à marcher jusqu’à ton futur chez toi pour éviter tous ces transports inconnus.",
      "leftText": "",
      "onLeft": "",
      "rightText": "",
      "onRight": "- 5 B - 10 H",
      "left_custom": "",
      "right_custom": "",
      "left_next_card": "",
      "right_next_card": "",
      "ordre": "",
      "difficulté": "",
      "Kanji": "",
      "background": "#e9f5f9",
      "image": "https://cdn-icons-png.flaticon.com/512/6594/6594737.png",
      "itemId": ""
    },
    {
      "Name": "rencontrer_proprio_1",
      "id": "0df94147ee8f4dfda5f631224e43e74d",
      "Molecule": "Rencontrer proprio",
      "Person": "e",
      "Status": "To Be checked",
      "card_type": "dialogue_card",
      "character": "proprio",
      "condition": "",
      "question": "Bienvenue ! Voici ton nouveau chez toi. J’habite juste à l’étage si tu as besoin de quoi que ce soit. D’ailleurs si tu n’as pas encore déjeuné viens dont prendre quelque chose !",
      "leftText": "Ah merci mais j’ai déjà mangé",
      "onLeft": "",
      "rightText": "Avec plaisir",
      "onRight": "+ 15 H + 5 B",
      "left_custom": "",
      "right_custom": "",
      "left_next_card": "",
      "right_next_card": "",
      "ordre": "",
      "difficulté": "",
      "Kanji": "",
      "background": "#e9f5f9",
      "image": "https://cdn-icons-png.flaticon.com/512/7697/7697533.png",
      "itemId": ""
    },
    {
      "Name": "rencontrer_papacrush_1",
      "id": "462b70a41b4847c6ad4e522af6b87733",
      "Molecule": "Rencontrer papacrush",
      "Person": "e",
      "Status": "To Be checked",
      "card_type": "dialogue_card",
      "character": "papacrush",
      "condition": "",
      "question": "Hmm. Je suis le fils de 女 . J’espère que vous n’êtes pas du genre à traîner dans le hall. Je n’aime pas du tout ça.",
      "leftText": "Vous êtes vraiment son fils ? Vous ne lui ressemblez pas du tout …",
      "onLeft": "-10 P",
      "rightText": "Euh non c’est pas mon genre",
      "onRight": "+5P",
      "left_custom": "",
      "right_custom": "",
      "left_next_card": "",
      "right_next_card": "",
      "ordre": "",
      "difficulté": "",
      "Kanji": "",
      "background": "#ccc",
      "image": "https://cdn-icons-png.flaticon.com/512/7504/7504950.png",
      "itemId": ""
    },
    {
      "Name": "rencontrer_voisinH_1",
      "id": "55dbbc6e0026488fbd97f24cf0bceb1a",
      "Molecule": "Rencontrer voisinH",
      "Person": "e",
      "Status": "To Be checked",
      "card_type": "dialogue_card",
      "character": "voisinshomme",
      "condition": "",
      "question": "Bonjour, vous êtes la nouvelle voisine je présume. Enchanté, j’habite en face avec ma femme 母 et mon fils 子. Passez une bonne journée.",
      "leftText": "Vous aussi",
      "onLeft": "+5P",
      "rightText": "… (fixer avec insistance)",
      "onRight": "-5P",
      "left_custom": "voisinh_existe",
      "right_custom": "voisinh_existe",
      "left_next_card": "",
      "right_next_card": "",
      "ordre": "",
      "difficulté": "",
      "Kanji": "",
      "background": "#ccc",
      "image": "https://cdn-icons-png.flaticon.com/512/3146/3146501.png",
      "itemId": ""
    },
    {
      "Name": "rencontrer_voisinF_1",
      "id": "293b2a80a53247baa5256000639dc933",
      "Molecule": "Rencontrer voisinF",
      "Person": "e",
      "Status": "To Be checked",
      "card_type": "dialogue_card",
      "character": "voisinsfemme",
      "condition": "",
      "question": "Bonjour, je suis votre voisine, vous avez peut être rencontré mon mari 父 ou mon fils 子. Si vous avez besoin d’aide n’hésitez pas à toquer chez nous!",
      "leftText": "Merci mais je n’ai besoin de l’aide de personne.",
      "onLeft": "+5B",
      "rightText": "Oh merci!",
      "onRight": "+5P",
      "left_custom": "voisinf_existe",
      "right_custom": "voisinf_existe",
      "left_next_card": "",
      "right_next_card": "",
      "ordre": "",
      "difficulté": "",
      "Kanji": "",
      "background": "#ccc",
      "image": "https://cdn-icons-png.flaticon.com/512/4486/4486352.png",
      "itemId": ""
    },
    {
      "Name": "rencontrer_voisinE_1",
      "id": "232662b3cb2a4080ac0ba214ef68b675",
      "Molecule": "Rencontrer voisinE",
      "Person": "e",
      "Status": "To Be checked",
      "card_type": "dialogue_card",
      "character": "enfantvoisin",
      "condition": "",
      "question": "Hé salut tu aimes les trains????",
      "leftText": "Euh oui ?",
      "onLeft": "+10P",
      "rightText": "Non c’est pour les enfants",
      "onRight": "-5P",
      "left_custom": "voisine_existe",
      "right_custom": "voisine_existe",
      "left_next_card": "",
      "right_next_card": "",
      "ordre": "",
      "difficulté": "",
      "Kanji": "",
      "background": "#ccc",
      "image": "https://cdn-icons-png.flaticon.com/512/1149/1149922.png",
      "itemId": ""
    },

    {
      "Name": "kombini_start_1",
      "id": "1f1d21e34eac4f9a8e25db5362de6f9b",
      "Molecule": "Kombini",
      "Person": "g",
      "Status": "",
      "card_type": "",
      "character": "vendeur",
      "condition": "first_time_kombini",
      "question": "Tu es arrivé au kombini. Une personne te crie dessus dès que tu entres.",
      "leftText": "Sursauter.\nLes gens sont fous ici.",
      "onLeft": "",
      "rightText": "Ne rien répondre.",
      "onRight": "",
      "left_custom": "jumpscared, !first_time_kombini",
      "right_custom": "no_jumpscare, !first_time_kombini",
      "left_next_card": "36a1fb3f88c94ad094fa150bcafed68f",
      "right_next_card": "36a1fb3f88c94ad094fa150bcafed68f",
      "ordre": "",
      "difficulté": "#ccc",
      "Kanji": "",
      "background": "#ccc",
      "image": "https://cdn-icons-png.flaticon.com/512/9190/9190361.png",
      "itemId": ""
    },
    {
      "Name": "kombini_start_2a",
      "id": "4566f4a78972445d9318c68add9acba0",
      "Molecule": "Kombini",
      "Person": "g",
      "Status": "",
      "card_type": "",
      "character": "",
      "condition": "jumpscared",
      "question": "Tu es devant le kombini. Tu hésites à entrer dans cette enseigne, mais tu as besoin d’acheter à manger.",
      "leftText": "Aller ailleurs.",
      "onLeft": "",
      "rightText": "Prenons notre courage à deux mains, et avançons !",
      "onRight": "",
      "left_custom": "",
      "right_custom": "!jumpscare, no_jumpscare",
      "left_next_card": "36a1fb3f88c94ad094fa150bcafed68f",
      "right_next_card": "36a1fb3f88c94ad094fa150bcafed68f",
      "ordre": "",
      "difficulté": "",
      "Kanji": "",
      "background": "#ccc",
      "image": "https://cdn-icons-png.flaticon.com/512/9190/9190361.png",
      "itemId": ""
    },
    {
      "Name": "kombini_start_2b",
      "id": "f664657568924ab495e562ea87fdf5ca",
      "Molecule": "Kombini",
      "Person": "g",
      "Status": "",
      "card_type": "",
      "character": "vendeur",
      "condition": "no_jumpscare",
      "question": "Tu entres dans le kombini. Le vendeur t’accueille avec entrain.",
      "leftText": "Ne rien répondre.",
      "onLeft": "",
      "rightText": "Saluer les bros, c’est bon, c’est la famille, c’est la maison !",
      "onRight": "Affinité vendeur+",
      "left_custom": "!no_jumpscare, irasshai_immunity",
      "right_custom": "!no_jumpscare, friends_with_cashier",
      "left_next_card": "36a1fb3f88c94ad094fa150bcafed68f",
      "right_next_card": "36a1fb3f88c94ad094fa150bcafed68f",
      "ordre": "",
      "difficulté": "",
      "Kanji": "",
      "background": "#ccc",
      "image": "https://cdn-icons-png.flaticon.com/512/9190/9190361.png",
      "itemId": ""
    },
    {
      "Name": "kombini_start_3a",
      "id": "d4a4e23916714f73a0a51764ce587069",
      "Molecule": "Kombini",
      "Person": "g",
      "Status": "",
      "card_type": "",
      "character": "vendeur",
      "condition": "irasshai_immunity",
      "question": "Tu entres dans le kombini.\nLe vendeur essaie de communiquer mais aucun son ne sort.",
      "leftText": "C’est étrange…",
      "onLeft": "",
      "rightText": "Commencer à acheter les nécessités.",
      "onRight": "",
      "left_custom": "!irasshai_immunity, irasshai_immunity_2",
      "right_custom": "",
      "left_next_card": "36a1fb3f88c94ad094fa150bcafed68f",
      "right_next_card": "36a1fb3f88c94ad094fa150bcafed68f",
      "ordre": "",
      "difficulté": "",
      "Kanji": "",
      "background": "#ccc",
      "image": "https://cdn-icons-png.flaticon.com/512/9190/9190361.png",
      "itemId": ""
    },
    {
      "Name": "kombini_start_3b",
      "id": "8da83b727a694ed6b4ba44a7cff1746a",
      "Molecule": "Kombini",
      "Person": "g",
      "Status": "",
      "card_type": "",
      "character": "vendeur",
      "condition": "friends_with_cashier",
      "question": "Tu entres dans le kombini. Le vendeur te sourit et te tend la main pour un check.",
      "leftText": "Ignorer.",
      "onLeft": "Affinité vendeur-",
      "rightText": "Check !",
      "onRight": "Affinité vendeur+",
      "left_custom": "no_jumpscare, !friends_with_cashier",
      "right_custom": "friends_with_cashier",
      "left_next_card": "36a1fb3f88c94ad094fa150bcafed68f",
      "right_next_card": "36a1fb3f88c94ad094fa150bcafed68f",
      "ordre": "",
      "difficulté": "",
      "Kanji": "",
      "background": "#ccc",
      "image": "https://cdn-icons-png.flaticon.com/512/9190/9190361.png",
      "itemId": ""
    },
    {
      "Name": "kombini_start_4a",
      "id": "bc1fa208a5934b8e8086d14c98af21e8",
      "Molecule": "Kombini",
      "Person": "g",
      "Status": "",
      "card_type": "",
      "character": "vendeur",
      "condition": "irasshai_immunity2",
      "question": "Tu entres dans le kombini.\nLe vendeur essaie visiblement de communiquer avec toi.",
      "leftText": "Ignorer.",
      "onLeft": "",
      "rightText": "S’arrêter pour essayer de comprendre.",
      "onRight": "",
      "left_custom": "irasshai_immunity, !irasshai_immunity_2",
      "right_custom": "!irasshai_immunity_2, no_jumpscare",
      "left_next_card": "36a1fb3f88c94ad094fa150bcafed68f",
      "right_next_card": "36a1fb3f88c94ad094fa150bcafed68f",
      "ordre": "",
      "difficulté": "",
      "Kanji": "",
      "background": "#ccc",
      "image": "https://cdn-icons-png.flaticon.com/512/9190/9190361.png",
      "itemId": ""
    },
    {
      "Name": "kombini_buy_easy",
      "id": "36a1fb3f88c94ad094fa150bcafed68f",
      "Molecule": "Kombini",
      "Person": "g",
      "Status": "",
      "card_type": "multiple_answer_card",
      "character": "",
      "condition": "",
      "question": "Que voulez-vous acheter ?",
      "leftText": "viande (肉)",
      "onLeft": "",
      "rightText": "poisson (魚)",
      "onRight": "",
      "left_custom": "",
      "right_custom": "",
      "left_next_card": "e2098d78628a49ad8c9a5d9cb04c8c87",
      "right_next_card": "e2098d78628a49ad8c9a5d9cb04c8c87",
      "ordre": "",
      "difficulté": "",
      "Kanji": "viande (肉), poisson (魚)",
      "background": "#ccc",
      "image": "https://cdn-icons-png.flaticon.com/512/9190/9190361.png",
      "itemId": ""
    },

    {
      "Name": "kombini_end_1",
      "id": "e2098d78628a49ad8c9a5d9cb04c8c87",
      "Molecule": "Kombini",
      "Person": "g",
      "Status": "",
      "card_type": "",
      "character": "vendeur",
      "condition": "",
      "question": "Tu t’apprêtes à sortir du kombini. Le vendeur te salue.\n”Maido.”",
      "leftText": "Presser le pas.",
      "onLeft": "",
      "rightText": "Ne rien répondre.",
      "onRight": "",
      "left_custom": "",
      "right_custom": "",
      "left_next_card": "",
      "right_next_card": "",
      "ordre": "",
      "difficulté": "",
      "Kanji": "",
      "background": "#ccc",
      "image": "https://cdn-icons-png.flaticon.com/512/9190/9190361.png",
      "itemId": ""
    },

    {
      "Name": "ecole_se_perdre_dans_les_couloirs",
      "id": "1dd0102cd9b848858925f3e9899379ce",
      "Molecule": "Premier jour à l’école",
      "Person": "e",
      "Status": "To Be checked",
      "card_type": "assessment_card",
      "character": "sans",
      "condition": "",
      "question": "Il semblerait que tu te sois perdu dans les couloirs… Pas malin ça tu risques d’arriver en retard.",
      "leftText": "je me depeche",
      "onLeft": "",
      "rightText": "booh flemme",
      "onRight": "",
      "left_custom": "",
      "right_custom": "",
      "left_next_card": "",
      "right_next_card": "",
      "ordre": "",
      "difficulté": "",
      "Kanji": "",
      "background": "#ccc",
      "image": "https://cdn-icons-png.flaticon.com/512/2231/2231696.png",
      "itemId": ""
    },
    {
      "Name": "rencontrer_crush_1",
      "id": "685ef582acb344faaa4fe4b680acd0f8",
      "Molecule": "Rencontrer crush",
      "Person": "e",
      "Status": "To Be checked",
      "card_type": "random_card",
      "character": "crush",
      "condition": "",
      "question": "Oh mais tu es nouveau toi ! Je suis 愛 la présidente du club de théâtre. Oh je suis aussi en classe 2-B c’est chouette on va pouvoir se recroiser!",
      "leftText": "J’ai trop hâte!!",
      "onLeft": "+10B",
      "rightText": "Merci c’est sympa, tu pourrais m’aider à trouver la salle?",
      "onRight": "+5B + 5P",
      "left_custom": "crush_existe",
      "right_custom": "crush_existe",
      "left_next_card": "",
      "right_next_card": "",
      "ordre": "",
      "difficulté": "",
      "Kanji": "",
      "background": "#ccc",
      "image": "https://cdn-icons-png.flaticon.com/512/1993/1993167.png",
      "itemId": ""
    },


    {
      "id": "3bc4abad722545aabcd9a01e30aaabcd",
      "Molecule": "Premier jour au japon",
      "card_type": "",
      "character": "",
      "condition": "",
      "question": "Wealthy looking young man asks you to throw a party in your kingdom.",
      "leftText": "oh no hoho",
      "onLeft": { happy: [], sad: ['joker'] },
      "rightText": "lets gooooo",
      "onRight": { happy: ['joker'], sad: [] },
      "left_custom": "",
      "right_custom": "",
      "left_next_card": "",
      "right_next_card": "",
      "ordre": "",
      "difficulté": "",
      "Kanji": "",
      "background": "#ccc",
      "image": "https://cdn-icons-png.flaticon.com/512/4276/4276749.png",
      "itemId": ""
    },

    {
      "id": "1a1681d447ac4562a19d1b10d9ecf137",
      "Molecule": "Premier jour au japon",
      "card_type": "",
      "character": "",
      "condition": "",
      "question": "Hunter from the near village requests some help. It seems like his hometown is in danger!!",
      "leftText": "Let him fight alone",
      "onLeft": { happy: [], sad: ['woman'] },
      "rightText": "Send the troops",
      "onRight": { happy: ['knight'], sad: [] },
      "left_custom": "",
      "right_custom": "",
      "left_next_card": "",
      "right_next_card": "",
      "ordre": "",
      "difficulté": "",
      "Kanji": "",
      "background": "#e9f5f9",
      "image": "https://cdn-icons-png.flaticon.com/512/6594/6594737.png",
      "itemId": ""
    },

    {
      "id": "d97ebf2a4a0f412dba7c2cfdbffff291",
      "Molecule": "Premier jour au japon",
      "card_type": "",
      "character": "",
      "condition": "",
      "question": "Your daughter wants a new pet.",
      "leftText": "Get her a cat",
      "onLeft": { happy: ['woman'], sad: [] },
      "rightText": "Get her a lion",
      "onRight": { happy: ['joker'], sad: ['woman'] },
      "left_custom": "",
      "right_custom": "",
      "left_next_card": "",
      "right_next_card": "",
      "ordre": "",
      "difficulté": "",
      "Kanji": "",
      "background": "#ccc",
      "image": "https://cdn-icons-png.flaticon.com/512/8592/8592791.png",
      "itemId": ""
    },

    {
      "id": "2db19f997a904d848fd2fd36d77d5404",
      "Molecule": "Premier jour au japon",
      "card_type": "",
      "character": "",
      "condition": "",
      "question": "Knights are bored because there is no war so they start to rob nearby villages",
      "leftText": "Get her a cat",
      "onLeft": { happy: ['woman'], sad: ['knight'] },
      "rightText": "Get her a lion",
      "onRight": { happy: ['joker', 'knight'], sad: ['woman'] },
      "left_custom": "",
      "right_custom": "",
      "left_next_card": "",
      "right_next_card": "",
      "ordre": "",
      "difficulté": "",
      "Kanji": "",
      "background": "#ccc",
      "image": "https://cdn-icons-png.flaticon.com/512/8794/8794740.png",
      "itemId": ""
    },

    {
      "id": "505dc8c39ed34f48ad448e8146dcb60e",
      "Molecule": "Premier jour au japon",
      "card_type": "",
      "character": "",
      "condition": "",
      "question": "He is probably a spy. Kill him",
      "leftText": "oh no hoho",
      "onLeft": { happy: [], sad: ['woman'] },
      "rightText": "Put him in the army",
      "onRight": { happy: ['knight'], sad: ['joker'] },
      "left_custom": "",
      "right_custom": "",
      "left_next_card": "",
      "right_next_card": "",
      "ordre": "",
      "difficulté": "",
      "Kanji": "",
      "background": "#ccc",
      "image": "https://cdn-icons-png.flaticon.com/512/9183/9183995.png",
      "itemId": ""
    },

    {
      "id": "e201fdaad5734c359a1910ac32886e56",
      "Molecule": "Premier jour au japon",
      "card_type": "",
      "character": "",
      "condition": "",
      "question": "just a test hehe",
      "leftText": "oh no hoho",
      "onLeft": { happy: [], sad: ['woman'] },
      "rightText": "lets gooooo",
      "onRight": { happy: ['knight'], sad: ['joker'] },
      "left_custom": "",
      "right_custom": "",
      "left_next_card": "",
      "right_next_card": "",
      "ordre": "",
      "difficulté": "",
      "Kanji": "",
      "background": "#ccc",
      "image": "https://cdn-icons-png.flaticon.com/512/7215/7215423.png",
      "itemId": ""
    },

 
  ];

  

  const getCardByIndex = (index) => {
    return Cards[index % Cards.length];
  };

  const getCardById = (id) => {
    return Cards.filter(function(Card) {return (Card.id == id);})[0];
  };

  return {
    Cards,
    getCardByIndex,
    getCardById,
  };
}
