export default function useGeneratedCards() {
  const Cards = [

    {
      "Name": "Introduction",
      "id": "505dc8c39ed34f48ad448e8146dcb60e",
      "Unit": "188b7fe299a045299d9ad38778b1c7a4",
      "Person": "e",
      "Status": "To Be checked",
      "card_type": "dialogue_card",
      "character": "persoexplication",
      "condition": {},
      "question": "Hé bien! Te voilà à Tokyo pour une année de cours à l’étranger. Je suis [trucname] et je veillerais à ce que ce ton séjour ici se passe parfaitement !",
      "leftText": "Oh !",
      "onLeft": "",
      "rightText": "Euh ?",
      "onRight": "",
      "custom":{},
      "left_custom": {},
      "right_custom": {},
      "left_next_card": "36f2fddae5f4434da9bc76f0763a28c2",
      "right_next_card": "36f2fddae5f4434da9bc76f0763a28c2",
      "difficulté": "",
      "Kanji": "",
      "background": "#ccc",
      "image": "https://cdn-icons-png.flaticon.com/512/9183/9183995.png",
      "itemId": ""
    },
    {
      "Name": "Introduction_tuto",
      "id": "36f2fddae5f4434da9bc76f0763a28c2",
      "Unit": "188b7fe299a045299d9ad38778b1c7a4",
      "Person": "e",
      "Status": "To Be checked",
      "card_type": "dialogue_card",
      "character": "persoexplication",
      "condition": {},
      "question": "Pour ce faire tu dois surveiller que ces jauges soient toujours pleines mais sans déborder ! Lors de ton année ces jauges varieront selon les choix que tu fais. Tiens essaie avec moi.",
      "leftText": "Acheter et manger un sandwich",
      "onLeft": "-5 A +10 H",
      "rightText": "Acheter un joli chapeau",
      "onRight": "-10 A +10 P + 10 B",
      "custom":{},
      "left_custom": {},
      "right_custom": {},
      "left_next_card": "703186931b994813ac8e89a5c2197fd3",
      "right_next_card": "703186931b994813ac8e89a5c2197fd3",
      "difficulté": "",
      "Kanji": "",
      "background": "#ccc",
      "image": "https://cdn-icons-png.flaticon.com/512/9183/9183995.png",
      "itemId": ""
    },
    {
      "Name": "Introduction_tuto_2",
      "id": "703186931b994813ac8e89a5c2197fd3",
      "Unit": "188b7fe299a045299d9ad38778b1c7a4",
      "Person": "e",
      "Status": "To Be checked",
      "card_type": "dialogue_card",
      "character": "persoexplication",
      "condition": {},
      "question": "Parfait ! Je suis certain que tu te débrouilleras parfaitement. Je passerais te voir de temps en temps.",
      "leftText": "A très vite!",
      "onLeft": "",
      "rightText": "ok bye",
      "onRight": "",
      "custom":{"chap1_intro":true},
      "left_custom":{},
      "right_custom": {},
      "left_next_card": "3bc4abad722545aabcd9a01e30aaabcd",
      "right_next_card": "3bc4abad722545aabcd9a01e30aaabcd",
      "difficulté": "",
      "Kanji": "",
      "background": "#ccc",
      "image": "https://cdn-icons-png.flaticon.com/512/9183/9183995.png",
      "itemId": ""
    },
    {
      "Name": "choix_transport",
      "id": "3bc4abad722545aabcd9a01e30aaabcd",
      "Unit": "86c6c8500ff246399c15db05cd986f7e",
      "Person": "",
      "Status": "",
      "card_type": "multiple_answer_card",
      "character": "sans",
      "condition":{},
      "question": "Comment souhaites tu te rendre à ton logement ?",
      "leftText": "marcher",
      "onLeft": "",
      "rightText": "prendre le métro",
      "onRight": "",
      "custom":{},
      "left_custom": {"chap1_street" : true, "chap1_choice_subway": false, "chap1_choice_taxi": false},
      "right_custom": {"chap1_choice_subway" : true, "chap1_choice_taxi": false},
      "left_next_card": "2db19f997a904d848fd2fd36d77d5404",
      "right_next_card": "d97ebf2a4a0f412dba7c2cfdbffff291",
      "difficulté": "",
      "Kanji": "marcher (足) voiture(車) train(電車)",
      "background": "#ccc",
      "image": "https://cdn-icons-png.flaticon.com/512/3267/3267450.png",
      "itemId": ""
    },
    {
      "Name": "choice_transport_taxi",
      "id": "0d1c3ea4d79e4c17962f0ca4d8af2549",
      "Unit": "Taxi",
      "Person": "e",
      "Status": "To Be checked",
      "card_type": "story_card",
      "character": "sans",
      "condition":{"chap1_street":false},
      "question": "C’était peut être cher mais tu es arrivé sans encombre. Le chauffeur était vachement bavard mais tu n’as pas compris un mot et tu t’es contenté de hocher la tête … Ah ! Il serait temps de prendre quelques cours.",
      "leftText": "ok",
      "onLeft": "",
      "rightText": "cool",
      "onRight": "-20 A + 5 B",
      "custom":{"chap1_choice_taxi":true},
      "left_custom": {},
      "right_custom": {},
      "left_next_card": "0df94147ee8f4dfda5f631224e43e74d",
      "right_next_card": "0df94147ee8f4dfda5f631224e43e74d",
      "difficulté": "",
      "Kanji": "",
      "background": "#ccc",
      "image": "https://cdn-icons-png.flaticon.com/512/3357/3357912.png",
      "itemId": ""
    },
    {
      "Name": "choice_transport_subway",
      "id": "d97ebf2a4a0f412dba7c2cfdbffff291",
      "Unit": "5bb712a2a85b4adfa4b5a4fd9756e821",
      "Person": "e",
      "Status": "To Be checked",
      "card_type": "story_card",
      "character": "sans",
      "condition":{"chap1_street":false},
      "question": "Pfiou! S’orienter dans une ville étrangère c’est éprouvant. Tous ces kanjis inconnus te donnent mal à la tête. Tu parviens tout de même à monter dans le métro que tu cherchais pour rentrer.",
      "leftText": "cool",
      "onLeft": "",
      "rightText": "super",
      "onRight": "-5 A - 5 B",
      "custom":{},
      "left_custom": {},
      "right_custom": {},
      "left_next_card": "",
      "right_next_card": "",
      "difficulté": "",
      "Kanji": "",
      "background": "#ccc",
      "image": "https://cdn-icons-png.flaticon.com/512/3313/3313514.png",
      "itemId": ""
    },
    {
      "Name": "Acheter_Pass",
      "id": "e5497ec82cf0475883608a25790bd700",
      "Unit": "5bb712a2a85b4adfa4b5a4fd9756e821",
      "Person": "l",
      "Status": "To Be checked",
      "card_type": "",
      "character": "sans",
      "condition": {"passSub_existe":false},
      "question": "Super tu as acheté ton premier pass !",
      "leftText": "Cool",
      "onLeft": "",
      "rightText": "",
      "onRight": "-10 A",
      "custom":{"passSub_existe":true},
      "left_custom": {},
      "right_custom": {},
      "left_next_card": "",
      "right_next_card": "",
      "difficulté": "",
      "Kanji": "",
      "background": "#ccc",
      "image": "https://cdn-icons-png.flaticon.com/512/3313/3313514.png",
      "itemId": ""
    },
    {
      "Name": "Se_tromper_station",
      "id": "2f60c8d820644133a999f7921edac2ab",
      "Unit": "5bb712a2a85b4adfa4b5a4fd9756e821",
      "Person": "l",
      "Status": "To Be checked",
      "card_type": "",
      "character": "sans",
      "condition":{},
      "question": "Mince ! Tu as fermé les yeux pendant deux secondes et loupé ta sation",
      "leftText": "Zut",
      "onLeft": "",
      "rightText": "Ma journée est ruinée",
      "onRight": "-5 B",
      "custom":{},
      "left_custom": {},
      "right_custom": {},
      "left_next_card": "",
      "right_next_card": "",
      "difficulté": "",
      "Kanji": "",
      "background": "#ccc",
      "image": "https://cdn-icons-png.flaticon.com/512/3313/3313514.png",
      "itemId": ""
    },
    {
      "Name": "Pervers_subway",
      "id": "aed04a6720c44c28a9142724c8a9ed71",
      "Unit": "5bb712a2a85b4adfa4b5a4fd9756e821",
      "Person": "l",
      "Status": "To Be checked",
      "card_type": "",
      "character": "sans",
      "condition":{},
      "question": "Un homme bizarre se colle à une femme",
      "leftText": "Ce ne sont pas mes affaires…",
      "onLeft": "",
      "rightText": "C’est terrible j’interviens",
      "onRight": "",
      "custom":{},
      "left_custom": {},
      "right_custom": {},
      "left_next_card": "",
      "right_next_card": "",
      "difficulté": "",
      "Kanji": "",
      "background": "#ccc",
      "image": "https://cdn-icons-png.flaticon.com/512/3313/3313514.png",
      "itemId": ""
    },
    {
      "Name": "choix_transport_marcher",
      "id": "2db19f997a904d848fd2fd36d77d5404",
      "Unit": "023f6b2981ff4853826039b6e1845e62",
      "Person": "e",
      "Status": "To Be checked",
      "card_type": "story_card",
      "character": "sans",
      "condition":{"arrive_home_completed" : false, "chap1_choice_subway" : false, "chap1_choice_subway" : false },
      "question": "Pfiou! S’orienter dans une ville étrangère c’est éprouvant. Tous ces kanjis inconnus ont eu raison de toi et te voilà à marcher jusqu’à ton futur chez toi pour éviter tous ces transports inconnus.",
      "leftText": "j'aime marcher",
      "onLeft": "",
      "rightText": "yes !",
      "onRight": "- 5 B - 10 H",
      "custom":{"chap1_choice_subway":false, "chap1_choice_taxi" : false},
      "left_custom": {},
      "right_custom": {},
      "left_next_card": "",
      "right_next_card": "",
      "difficulté": "",
      "Kanji": "",
      "background": "#ccc",
      "image": "https://cdn-icons-png.flaticon.com/512/6594/6594737.png",
      "itemId": ""
    },
    {
      "Name": "rencontrer_proprio_1",
      "id": "0df94147ee8f4dfda5f631224e43e74d",
      "Unit": "1e3a7a782b9f42f2a63f4a4be85cc08a",
      "Person": "e",
      "Status": "To Be checked",
      "card_type": "dialogue_card",
      "character": "proprio",
      "condition": {"proprio_existe":false},
      "question": "Bienvenue ! Voici ton nouveau chez toi. J’habite juste à l’étage si tu as besoin de quoi que ce soit. D’ailleurs si tu n’as pas encore déjeuné viens dont prendre quelque chose !",
      "leftText": "Ah merci mais j’ai déjà mangé",
      "onLeft": "",
      "rightText": "Avec plaisir",
      "onRight": "+ 15 H + 5 B",
      "custom":{"proprio_existe":true,},
      "left_custom": {},
      "right_custom": {},
      "left_next_card": "",
      "right_next_card": "",
      "difficulté": "",
      "Kanji": "",
      "background": "#ccc",
      "image": "https://cdn-icons-png.flaticon.com/512/7697/7697533.png",
      "itemId": ""
    },
    {
      "Name": "Activity_1",
      "id": "9d1174e62e5d44f7a95c460745307e23",
      "Unit": "99c3d8e19fab41db9d08c158a84e9e7e",
      "Person": "l",
      "Status": "To Be checked",
      "card_type": "",
      "character": "",
      "condition":{},
      "question": "Que souhaites tu faire maintenant ?",
      "leftText": "Je vais me balader dehors",
      "onLeft": "",
      "rightText": "Je vais rester à la maison",
      "onRight": "",
      "custom":{},
      "left_custom": {"chap1_street" : false},
      "right_custom": {"chap1_street" : true, "at_Home" : true},
      "left_next_card": "",
      "right_next_card": "99888040bcc54e269ca6d0099d80979d",
      "difficulté": "",
      "Kanji": "",
      "background": "#ccc",
      "image": "https://cdn-icons-png.flaticon.com/512/953/953716.png",
      "itemId": ""
    },
    {
      "Name": "Regarder_TV",
      "id": "99888040bcc54e269ca6d0099d80979d",
      "Unit": "94a786f5d9e1405ca02b094fee0a9ece",
      "Person": "l",
      "Status": "To Be checked",
      "card_type": "",
      "character": "sans",
      "condition": {"at_Home":true},
      "question": "Tu regardes les infos",
      "leftText": "C’est un peu ennuyant",
      "onLeft": "",
      "rightText": "J’ai rien compris",
      "onRight": "",
      "custom":{"at_Home": false},
      "left_custom": {},
      "right_custom": {},
      "left_next_card": "",
      "right_next_card": "",
      "difficulté": "",
      "Kanji": "",
      "background": "#ccc",
      "image": "https://cdn-icons-png.flaticon.com/512/4784/4784962.png",
      "itemId": ""
    },
    {
      "Name": "rencontrer_papacrush_1",
      "id": "462b70a41b4847c6ad4e522af6b87733",
      "Unit": "a128e9e5a4814e258aaa6e9f358ed131",
      "Person": "e",
      "Status": "To Be checked",
      "card_type": "dialogue_card",
      "character": "papacrush",
      "condition": {"papacrush_existe":false},
      "question": "Hmm. Je suis le fils de 女 . J’espère que vous n’êtes pas du genre à traîner dans le hall. Je n’aime pas du tout ça.",
      "leftText": "Vous êtes vraiment son fils ? Vous ne lui ressemblez pas du tout …",
      "onLeft": "-10 P",
      "rightText": "Euh non c’est pas mon genre",
      "onRight": "+5P",
      "custom":{"papacrush_existe":true, "crush_dad" : true},
      "left_custom": {},
      "right_custom": {},
      "left_next_card": "",
      "right_next_card": "",
      "difficulté": "",
      "Kanji": "女 (femme)",
      "background": "#ccc",
      "image": "https://cdn-icons-png.flaticon.com/512/7504/7504950.png",
      "itemId": ""
    },
    {
      "Name": "rencontrer_voisinH_1",
      "id": "55dbbc6e0026488fbd97f24cf0bceb1a",
      "Unit": "e8da1ec1d29a40ebb1e8df654f1e21fd",
      "Person": "e",
      "Status": "To Be checked",
      "card_type": "dialogue_card",
      "character": "voisinshomme",
      "condition": {"voisinh_existe":false},
      "question": "Bonjour, vous êtes la nouvelle voisine je présume. Enchanté, j’habite en face avec ma femme 母 et mon fils 子. Passez une bonne journée.",
      "leftText": "Vous aussi",
      "onLeft": "+5P",
      "rightText": "… (fixer avec insistance)",
      "onRight": "-5P",
      "custom":{"voisinh_existe":true, "neighbourH" : true},
      "left_custom": {},
      "right_custom": {},
      "left_next_card": "",
      "right_next_card": "",
      "difficulté": "",
      "Kanji": "母 (mère) 子 (enfant)",
      "background": "#ccc",
      "image": "https://cdn-icons-png.flaticon.com/512/3146/3146501.png",
      "itemId": ""
    },
    {
      "Name": "rencontrer_voisinF_1",
      "id": "293b2a80a53247baa5256000639dc933",
      "Unit": "eb4f9491cb39453585760a4740a1c3a3",
      "Person": "e",
      "Status": "To Be checked",
      "card_type": "dialogue_card",
      "character": "voisinsfemme",
      "condition": {"voisinf_existe":false},
      "question": "Bonjour, je suis votre voisine, vous avez peut être rencontré mon mari 父 ou mon fils 子. Si vous avez besoin d’aide n’hésitez pas à toquer chez nous!",
      "leftText": "Merci mais je n’ai besoin de l’aide de personne.",
      "onLeft": "+5B",
      "rightText": "Oh merci!",
      "onRight": "+5P",
      "custom":{"voisinf_existe":true, "neighbourF" : true},
      "left_custom": {},
      "right_custom": {},
      "left_next_card": "",
      "right_next_card": "",
      "difficulté": "",
      "Kanji": "父 (père)  子 (enfant)",
      "background": "#ccc",
      "image": "https://cdn-icons-png.flaticon.com/512/4486/4486352.png",
      "itemId": ""
    },
    {
      "Name": "rencontrer_voisinE_1",
      "id": "232662b3cb2a4080ac0ba214ef68b675",
      "Unit": "389e55e44050475fb11e8d0aae694b13",
      "Person": "e",
      "Status": "To Be checked",
      "card_type": "dialogue_card",
      "character": "enfantvoisin",
      "condition": {"voisine_existe":false},
      "question": "Hé salut tu aimes les trains????",
      "leftText": "Euh oui ?",
      "onLeft": "+10P",
      "rightText": "Non c’est pour les enfants",
      "onRight": "-5P",
      "custom":{"voisine_existe":true, "neighbourE" : true},
      "left_custom": {},
      "right_custom": {},
      "left_next_card": "",
      "right_next_card": "",
      "difficulté": "",
      "Kanji": "",
      "background": "#ccc",
      "image": "https://cdn-icons-png.flaticon.com/512/1149/1149922.png",
      "itemId": ""
    },
    {
      "Name": "ecole_se_perdre_dans_les_couloirs",
      "id": "1dd0102cd9b848858925f3e9899379ce",
      "Unit": "School",
      "Person": "e",
      "Status": "To Be checked",
      "card_type": "assessment_card",
      "character": "sans",
      "condition":{},
      "question": "Il semblerait que tu te sois perdu dans les couloirs… Pas malin ça tu risques d’arriver en retard.",
      "leftText": "",
      "onLeft": "",
      "rightText": "",
      "onRight": "",
      "custom":{},
      "left_custom": {},
      "right_custom": {},
      "left_next_card": "",
      "right_next_card": "",
      "difficulté": "",
      "Kanji": "",
      "background": "#ccc",
      "image": "",
      "itemId": ""
    },
    {
      "Name": "rencontrer_crush_1",
      "id": "685ef582acb344faaa4fe4b680acd0f8",
      "Unit": "7c00e48218bc42aea11107d0f21f90c3",
      "Person": "e",
      "Status": "To Be checked",
      "card_type": "random_card",
      "character": "crush",
      "condition": {"crush_existe":false},
      "question": "Oh mais tu es nouveau toi ! Je suis 愛 la présidente du club de théâtre. Oh je suis aussi en classe 2-B c’est chouette on va pouvoir se recroiser!",
      "leftText": "J’ai trop hâte!!",
      "onLeft": "+10B",
      "rightText": "Merci c’est sympa, tu pourrais m’aider à trouver la salle?",
      "onRight": "+5B + 5P",
      "custom":{"crush_existe":true},
      "left_custom": {},
      "right_custom": {},
      "left_next_card": "",
      "right_next_card": "",
      "difficulté": "",
      "Kanji": "愛 (amour)",
      "background": "#ccc",
      "image": "https://cdn-icons-png.flaticon.com/512/1993/1993167.png",
      "itemId": ""
    },

    {
      "card_type": "",
      "Person": "",
      "Name": "introduction_chap2_1",
      "id": "66262f990e88413f9ed6c66ab83d5300",
      "unit": "68bad6fc747141d1beb35ee057858f67",
      "Status": "",
      "character": "",
      "condition": "",
      "question": "Oh la la c’est un seisme qui se prépare ou ton ventre que j’entend ?!",
      "leftText": "Je ne te permets pas",
      "onLeft": "",
      "rightText": "Oui j’ai un peu faim…",
      "onRight": "",
      "custom":{},
      "left_custom": {},
      "right_custom": {},
      "left_next_card": "",
      "right_next_card": "",
      "difficulté": "",
      "Kanji": "",
      "background": "#ccc",
      "image": "https://cdn-icons-png.flaticon.com/512/9183/9183995.png",
      "itemId": ""
    },
    {
      "card_type": "",
      "Person": "",
      "Name": "introduction_chap2_2",
      "id": "76b5bfc9afb64c5babf9350ad8c81bb7",
      "unit": "68bad6fc747141d1beb35ee057858f67",
      "Status": "",
      "character": "",
      "condition": "",
      "question": "Bon ça tombe bien, tu pourras préprarer ton premier plat japonais aujourd’hui !",
      "leftText": "Ça existe pas Uber Eats au Japon ?",
      "onLeft": "",
      "rightText": "Ok j’ai hâte !",
      "onRight": "",
      "custom":{},
      "left_custom": {},
      "right_custom": {},
      "left_next_card": "",
      "right_next_card": "",
      "difficulté": "",
      "Kanji": "",
      "background": "#ccc",
      "image": "https://cdn-icons-png.flaticon.com/512/9183/9183995.png",
      "itemId": ""
    },
    {
      "card_type": "",
      "Person": "",
      "Name": "Hungry_1",
      "id": "b763de33a9f0457ea2db2a20a0e1e57a",
      "unit": "28662fe73d694abbbc153e72ba25596d",
      "Status": "",
      "character": "",
      "condition": "",
      "question": "Ton ventre gargouille…",
      "leftText": "Je vais aller cuisiner",
      "onLeft": "",
      "rightText": "Allons faire les courses",
      "onRight": "",
      "custom":{},
      "left_custom": {},
      "right_custom": {},
      "left_next_card": "",
      "right_next_card": "",
      "difficulté": "",
      "Kanji": "",
      "background": "#ccc",
      "image": "https://cdn-icons-png.flaticon.com/512/5060/5060720.png",
      "itemId": ""
    },
    {
      "card_type": "",
      "Person": "",
      "Name": "Library_1",
      "id": "a0da9bacb9c147ad946b90001d355e8f",
      "unit": "7d6c2f8046bb475a8f7a119e924a8452",
      "Status": "",
      "character": "",
      "condition": "",
      "question": "Que veux tu emprunter ?",
      "leftText": "Un livre de recettes",
      "onLeft": "",
      "rightText": "Le dernier tome de My Hero Academia",
      "onRight": "",
      "custom":{},
      "left_custom": {},
      "right_custom": {},
      "left_next_card": "",
      "right_next_card": "",
      "difficulté": "",
      "Kanji": "",
      "background": "#ccc",
      "image": "https://cdn-icons-png.flaticon.com/512/3660/3660258.png",
      "itemId": ""
    },
    {
      "card_type": "",
      "Person": "",
      "Name": "Grocery_store_1",
      "id": "479dfbcc62c443d8a1d5501f09edcca8",
      "unit": "54b40bf6f6204fc0a0d84f66b3795381",
      "Status": "",
      "character": "",
      "condition": "",
      "question": "Que veux tu acheter",
      "leftText": "Des oeufs",
      "onLeft": "",
      "rightText": "Des carottes",
      "onRight": "",
      "custom":{},
      "left_custom": {},
      "right_custom": {},
      "left_next_card": "",
      "right_next_card": "",
      "difficulté": "",
      "Kanji": "",
      "background": "#ccc",
      "image": "https://cdn-icons-png.flaticon.com/512/610/610365.png",
      "itemId": ""
    },
    {
      "card_type": "",
      "Person": "",
      "Name": "Cook_1",
      "id": "6a113b437caf4e6f932c2cbfb4ca79a2",
      "unit": "810d9da937e2464ab5b7145a73050996",
      "Status": "",
      "character": "",
      "condition": "",
      "question": "Bravo tu as fait un omurice !",
      "leftText": "Miam !",
      "onLeft": "",
      "rightText": "Je vais me régaler",
      "onRight": "",
      "custom":{},
      "left_custom": {},
      "right_custom": {},
      "left_next_card": "",
      "right_next_card": "",
      "difficulté": "",
      "Kanji": "",
      "background": "#ccc",
      "image": "https://cdn-icons-png.flaticon.com/512/3362/3362029.png",
      "itemId": ""
    },

    {
      "Name": "rencontrer_bro_1",
      "id": "3ec5a10e661b4c198e533f04f30f942b",
      "Unit": "bro",
      "Person": "e",
      "Status": "To Be checked",
      "card_type": "random_card",
      "character": "brosûr",
      "condition": {"bro_existe":false},
      "question": "Hello c’est toi le nouveau ? Je suis en 2-B aussi et je m’appelle 友. Jparie qu’on va bien s’entendre !",
      "leftText": "c’est certain !",
      "onLeft": "+10B + 10P",
      "rightText": "Oui ok mais là je suis pressé",
      "onRight": "-5P + -5B",
      "custom":{"bro_existe":true},
      "left_custom": {},
      "right_custom": {},
      "left_next_card": "",
      "right_next_card": "",
      "difficulté": "",
      "Kanji": "",
      "background": "#ccc",
      "image": "",
      "itemId": ""
    },
    {
      "Name": "rencontrer_bully_1",
      "id": "e201fdaad5734c359a1910ac32886e56",
      "Unit": "School",
      "Person": "e",
      "Status": "To Be checked",
      "card_type": "random_card",
      "character": "bully",
      "condition": {"bully_existe":false},
      "question": "Pff donc c’est toi le nouveau? Tu n’as rien de spécial. Hors de ma vue tu gâches le paysage",
      "leftText": "désolée …",
      "onLeft": "-10P - 10B",
      "rightText": "Non c’est toi qui gâches le paysage",
      "onRight": "+5P",
      "custom":{"bully_existe":true},
      "left_custom": {},
      "right_custom": {},
      "left_next_card": "",
      "right_next_card": "",
      "difficulté": "",
      "Kanji": "",
      "background": "#ccc",
      "image": "",
      "itemId": ""
    },
    {
      "Name": "rencontrer_prezmus_1",
      "id": "1ac1fa6a2bdf4748b35d056e3bbe7a24",
      "Unit": "School",
      "Person": "e",
      "Status": "To Be checked",
      "card_type": "dialogue_card",
      "character": "prezmusique",
      "condition": {"prezmus_existe":false},
      "question": "Oh salut! Tu sais jouer d’un instrument ou tu veux apprendre ? Je suis justement la président du club musique alors n’hésite pas à t’inscrire !",
      "leftText": "L’apprentissage d’un instrument est une perte de temps",
      "onLeft": "-5P",
      "rightText": "Oh oui j’aimerais bien apprendre à jouer d’un instrument!",
      "onRight": "+5P",
      "custom":{"prezmus_existe":true},
      "left_custom": {},
      "right_custom":{} ,
      "left_next_card": "",
      "right_next_card": "",
      "difficulté": "",
      "Kanji": "",
      "background": "#ccc",
      "image": "",
      "itemId": ""
    },
    {
      "Name": "rencontrer_prezsport_1",
      "id": "088b2294323c4352bb97ec2d21a743fc",
      "Unit": "School",
      "Person": "e",
      "Status": "To Be checked",
      "card_type": "dialogue_card",
      "character": "prezsport",
      "condition": {"prezsport_existe":false},
      "question": "Oyooooooo t’es nouveau et t’as envie de t’échauffer les bibis? T’es tombé sur la bonne personne mon gars je suis le président du club de sport ! Viens t’inscrire direeect",
      "leftText": "Euh les … bibis ?",
      "onLeft": "-5P",
      "rightText": "J’y penserais merci !",
      "onRight": "+5P",
      "custom": {"prezsport_existe":true},
      "left_custom": {},
      "right_custom": {},
      "left_next_card": "",
      "right_next_card": "",
      "difficulté": "",
      "Kanji": "",
      "background": "#ccc",
      "image": "",
      "itemId": ""
    },
    {
      "Name": "rencontrer_prezpeint_1",
      "id": "8a546bbe5ce94e67a67cfe3c94d36abf",
      "Unit": "School",
      "Person": "e",
      "Status": "To Be checked",
      "card_type": "dialogue_card",
      "character": "prezpeinture",
      "condition": {"prezpeint_existe":false},
      "question": "Salut… Je suis le président du club de peinture, mon nom est 画. J’espère qu’on se recroisera …",
      "leftText": "Je manquerais pas de venir faire un tour au club !",
      "onLeft": "+5B",
      "rightText": "Ça m’a tout l’air d’être un club de gros loosers",
      "onRight": "-10P",
      "custom": {"prezpeint_existe":true},
      "left_custom": {},
      "right_custom": {},
      "left_next_card": "",
      "right_next_card": "",
      "difficulté": "",
      "Kanji": "“画” dessin",
      "background": "#ccc",
      "image": "",
      "itemId": ""
    },
    {
      "Name": "rencontrer_prezcui_1",
      "id": "7b7bdb75779d4a439d16b86160b432a0",
      "Unit": "School",
      "Person": "e",
      "Status": "To Be checked",
      "card_type": "dialogue_card",
      "character": "prezcuisine",
      "condition": {"prezcui_existe":false},
      "question": "Salut toi ! Je suis la présidente du club de cuisine je serais ravie de t’apprendre à faire plein de plats délicieux ! Si ça te dit n’hésite pas à passer me voir !",
      "leftText": "Ça a l’air super chouette, j’arrrrrive!!!",
      "onLeft": "+5P +5B",
      "rightText": "Euh j’ai pas vraiment la fibre culinaire … Je laisse ça aux autres …",
      "onRight": "-5B",
      "custom": {"prezcui_existe":true},
      "left_custom": {},
      "right_custom": {},
      "left_next_card": "",
      "right_next_card": "",
      "difficulté": "",
      "Kanji": "",
      "background": "#ccc",
      "image": "",
      "itemId": ""
    },
    {
      "Name": "rencontrer_prezweeb_1",
      "id": "4dfcbeeae33b4c6fb62360cd9c7e491b",
      "Unit": "School",
      "Person": "e",
      "Status": "To Be checked",
      "card_type": "",
      "character": "prezweeb",
      "condition": {"prezweeb_existe":false},
      "question": "Ah c’est toi le nouveau dont tout le monde parle, je te rencontre ENFIN !!! Dis je tiens un super club on est dans la salle du fond juste à côté du club musique hésite pas à venir t’inscrire !",
      "leftText": "Heu un club de quoi ?",
      "onLeft": "",
      "rightText": "T’as l’air d’être un chouette type je viendrais m’inscrire !",
      "onRight": "+5B + 5P",
      "custom": {"prezweeb_existe":true},
      "left_custom": {},
      "right_custom": {},
      "left_next_card": "",
      "right_next_card": "",
      "difficulté": "",
      "Kanji": "",
      "background": "",
      "image": "",
      "itemId": ""
    },
    {
      "Name": "rencontrer_prezweeb_2",
      "id": "2845e7a0e4aa4c878fa1c34547aa5c86",
      "Unit": "School",
      "Person": "e",
      "Status": "",
      "card_type": "",
      "character": "prezweeb",
      "condition":{},
      "question": "Heuuu … C’est à dire qu’on a beaucoup de sujets ensemble y’a vraiment plein de trucs intéressants c’est dur d’en choisir un en particulier là comme ça … Euhh !! On a une bibliothèque pleine de mangas aussi!!",
      "leftText": "Ah s’il y a des mangas ça m’intéresse !",
      "onLeft": "+5B",
      "rightText": "Louche ton truc, on dirait que t’as quelque chose à cacher.",
      "onRight": "",
      "custom":{},
      "left_custom": {},
      "right_custom": {},
      "left_next_card": "",
      "right_next_card": "",
      "difficulté": "",
      "Kanji": "",
      "background": "",
      "image": "",
      "itemId": ""
    },
    {
      "Name": "rencontrer_prof",
      "id": "fe9293df5867473cb60560e3886d6dac",
      "Unit": "School",
      "Person": "e",
      "Status": "To Be checked",
      "card_type": "dialogue_card",
      "character": "prof",
      "condition": {"prof_existe":false},
      "question": "Bienvenue au lycée [lycée_name]",
      "leftText": "",
      "onLeft": "",
      "rightText": "",
      "onRight": "",
      "custom": {"prof_existe":true},
      "left_custom": {},
      "right_custom": {},
      "left_next_card": "",
      "right_next_card": "",
      "difficulté": "",
      "Kanji": "",
      "background": "#ccc",
      "image": "",
      "itemId": ""
    },
    {
      "Name": "ecole_introduction_classe",
      "id": "8b391439bae34fd786ed4712e60cfc7a",
      "Unit": "Classroom",
      "Person": "e",
      "Status": "",
      "card_type": "story_card",
      "character": "",
      "condition":{},
      "question": "Bonjour",
      "leftText": "",
      "onLeft": "",
      "rightText": "",
      "onRight": "",
      "custom":{},
      "left_custom": {},
      "right_custom": {},
      "left_next_card": "",
      "right_next_card": "",
      "difficulté": "",
      "Kanji": "",
      "background": "#ccc",
      "image": "",
      "itemId": ""
    },
    {
      "Name": "ecole_premier_cours",
      "id": "fcec37e04abe43c4a919f3b336029576",
      "Unit": "First_lesson",
      "Person": "",
      "Status": "",
      "card_type": "story_card",
      "character": "",
      "condition":{},
      "question": "Bienvenue au premier cours",
      "leftText": "",
      "onLeft": "",
      "rightText": "",
      "onRight": "",
      "custom":{},
      "left_custom": {},
      "right_custom": {},
      "left_next_card": "",
      "right_next_card": "",
      "difficulté": "",
      "Kanji": "",
      "background": "#ccc",
      "image": "",
      "itemId": ""
    },
    {
      "Name": "ami_approche",
      "id": "a632b16867384d45ab0f0fc3c45861d7",
      "Unit": "Se faire un ami",
      "Person": "",
      "Status": "",
      "card_type": "story_card",
      "character": "",
      "condition":{},
      "question": "Bonjour",
      "leftText": "",
      "onLeft": "",
      "rightText": "",
      "onRight": "",
      "custom":{},
      "left_custom": {},
      "right_custom": {},
      "left_next_card": "b2632f1abb374ab1990e0a77bb99b5e2",
      "right_next_card": "",
      "difficulté": "",
      "Kanji": "",
      "background": "#ccc",
      "image": "",
      "itemId": ""
    },
    {
      "Name": "ami_intro",
      "id": "b2632f1abb374ab1990e0a77bb99b5e2",
      "Unit": "Se faire un ami",
      "Person": "",
      "Status": "",
      "card_type": "dialogue_card",
      "character": "",
      "condition":{},
      "question": "Bonjour",
      "leftText": "",
      "onLeft": "",
      "rightText": "",
      "onRight": "",
      "custom":{},
      "left_custom": {},
      "right_custom": {},
      "left_next_card": "ee137cbf80684423a224450bb2f827dc",
      "right_next_card": "",
      "difficulté": "",
      "Kanji": "",
      "background": "#ccc",
      "image": "",
      "itemId": ""
    },
    {
      "Name": "ami_intro_club",
      "id": "ee137cbf80684423a224450bb2f827dc",
      "Unit": "Se faire un ami",
      "Person": "",
      "Status": "",
      "card_type": "dialogue_card",
      "character": "",
      "condition":{},
      "question": "Viens au club",
      "leftText": "",
      "onLeft": "",
      "rightText": "",
      "onRight": "",
      "custom":{},
      "left_custom": {},
      "right_custom": {},
      "left_next_card": "005dce90775841168e676d1589b094fa",
      "right_next_card": "",
      "difficulté": "",
      "Kanji": "",
      "background": "#ccc",
      "image": "",
      "itemId": ""
    },
    {
      "Name": "ami_intro_classe",
      "id": "005dce90775841168e676d1589b094fa",
      "Unit": "Se faire un ami",
      "Person": "",
      "Status": "",
      "card_type": "dialogue_card",
      "character": "",
      "condition":{},
      "question": "Ami ami",
      "leftText": "",
      "onLeft": "",
      "rightText": "",
      "onRight": "",
      "custom":{},
      "left_custom": {},
      "right_custom": {},
      "left_next_card": "5d8a229a4144468991f2a2ba33dc52d3",
      "right_next_card": "",
      "difficulté": "",
      "Kanji": "",
      "background": "#ccc",
      "image": "",
      "itemId": ""
    },
    {
      "Name": "ami_dejeuner",
      "id": "5d8a229a4144468991f2a2ba33dc52d3",
      "Unit": "Se faire un ami",
      "Person": "",
      "Status": "",
      "card_type": "dialogue_card",
      "character": "",
      "condition":{},
      "question": "On déjeune",
      "leftText": "",
      "onLeft": "",
      "rightText": "",
      "onRight": "",
      "custom":{},
      "left_custom": {},
      "right_custom": {},
      "left_next_card": "",
      "right_next_card": "",
      "difficulté": "",
      "Kanji": "",
      "background": "#ccc",
      "image": "",
      "itemId": ""
    },
    {
      "Name": "cours_lecon",
      "id": "7d1444c235c442a5ba6e115a0b4345d4",
      "Unit": "Cours",
      "Person": "",
      "Status": "",
      "card_type": "recurrent_card",
      "character": "",
      "condition":{},
      "question": "C'est une leçon",
      "leftText": "",
      "onLeft": "",
      "rightText": "",
      "onRight": "",
      "custom":{},
      "left_custom": {},
      "right_custom": {},
      "left_next_card": "8c70fbab291e465ea33fb6dd9c3f1dfb",
      "right_next_card": "",
      "difficulté": "",
      "Kanji": "",
      "background": "#ccc",
      "image": "",
      "itemId": ""
    },
    {
      "Name": "cours_test",
      "id": "8c70fbab291e465ea33fb6dd9c3f1dfb",
      "Unit": "Cours",
      "Person": "",
      "Status": "",
      "card_type": "recurrent_card",
      "character": "",
      "condition":{},
      "question": "C'est un test",
      "leftText": "",
      "onLeft": "",
      "rightText": "",
      "onRight": "",
      "custom":{},
      "left_custom": {},
      "right_custom": {},
      "left_next_card": "",
      "right_next_card": "",
      "difficulté": "",
      "Kanji": "",
      "background": "#ccc",
      "image": "",
      "itemId": ""
    },
    {
      "Name": "kombini_start_1",
      "id": "1f1d21e34eac4f9a8e25db5362de6f9b",
      "Unit": "092e7b31cd7a46a79a6d79f40d743a78",
      "Person": "g",
      "Status": "",
      "card_type": "",
      "character": "vendeur",
      "condition": {"first_time_kombini":true},
      "question": "Tu es arrivé au kombini. Une personne te crie dessus dès que tu entres.",
      "leftText": "Sursauter.\nLes gens sont fous ici.",
      "onLeft": "",
      "rightText": "Ne rien répondre.",
      "onRight": "",
      "custom":{},
      "left_custom": {"jumpscare":true, "first_time_kombini":false},
      "right_custom": {"jumpscare":false, "first_time_kombini":false},
      "left_next_card": "",
      "right_next_card": "",
      "difficulté": "",
      "Kanji": "",
      "background": "#ccc",
      "image": "https://cdn-icons-png.flaticon.com/512/9190/9190361.png",
      "itemId": ""
    },
    {
      "Name": "kombini_start_2a",
      "id": "4566f4a78972445d9318c68add9acba0",
      "Unit": "092e7b31cd7a46a79a6d79f40d743a78",
      "Person": "g",
      "Status": "",
      "card_type": "",
      "character": "",
      "condition": {"jumpscare":true},
      "question": "Tu es devant le kombini. Tu hésites à entrer dans cette enseigne, mais tu as besoin d’acheter à manger.",
      "leftText": "Aller ailleurs.",
      "onLeft": "",
      "rightText": "Prenons notre courage à deux mains, et avançons !",
      "onRight": "",
      "custom":{},
      "left_custom": {},
      "right_custom": {"jumpscare":false},
      "left_next_card": "",
      "right_next_card": "",
      "difficulté": "",
      "Kanji": "",
      "background": "#ccc",
      "image": "https://cdn-icons-png.flaticon.com/512/9190/9190361.png",
      "itemId": ""
    },
    {
      "Name": "kombini_start_2b",
      "id": "f664657568924ab495e562ea87fdf5ca",
      "Unit": "092e7b31cd7a46a79a6d79f40d743a78",
      "Person": "g",
      "Status": "",
      "card_type": "",
      "character": "vendeur",
      "condition": {"jumpscare":false},
      "question": "Tu entres dans le kombini. Le vendeur t’accueille avec entrain.",
      "leftText": "Ne rien répondre.",
      "onLeft": "",
      "rightText": "Saluer les bros, c’est bon, c’est la famille, c’est la maison !",
      "onRight": "",
      "custom":{},
      "left_custom": {"jumpscare":true, "irasshai_immunity":true},
      "right_custom": {"jumpscare":false, "friends_with_cashier":true},
      "left_next_card": "",
      "right_next_card": "",
      "difficulté": "",
      "Kanji": "",
      "background": "#ccc",
      "image": "https://cdn-icons-png.flaticon.com/512/9190/9190361.png",
      "itemId": ""
    },
    {
      "Name": "kombini_start_3a",
      "id": "d4a4e23916714f73a0a51764ce587069",
      "Unit": "092e7b31cd7a46a79a6d79f40d743a78",
      "Person": "g",
      "Status": "",
      "card_type": "",
      "character": "vendeur",
      "condition": {"irasshai_immunity":true},
      "question": "Tu entres dans le kombini.\nLe vendeur essaie de communiquer mais aucun son ne sort.",
      "leftText": "C’est étrange…",
      "onLeft": "",
      "rightText": "Commencer à acheter les nécessités.",
      "onRight": "",
      "custom":{},
      "left_custom": {"irasshai_immunity":false, "irasshai_immunity_2":true},
      "right_custom": {},
      "left_next_card": "",
      "right_next_card": "",
      "difficulté": "",
      "Kanji": "",
      "background": "#ccc",
      "image": "https://cdn-icons-png.flaticon.com/512/9190/9190361.png",
      "itemId": ""
    },
    {
      "Name": "kombini_start_3b",
      "id": "8da83b727a694ed6b4ba44a7cff1746a",
      "Unit": "092e7b31cd7a46a79a6d79f40d743a78",
      "Person": "g",
      "Status": "",
      "card_type": "",
      "character": "vendeur",
      "condition": {"friends_with_cashier":true},
      "question": "Tu entres dans le kombini. Le vendeur te sourit et te tend la main pour un check.",
      "leftText": "Ignorer.",
      "onLeft": "",
      "rightText": "Check !",
      "onRight": "",
      "custom":{},
      "left_custom": {"jumpscare":true, "friends_with_cashier":false},
      "right_custom": {"friends_with_cashier":true},
      "left_next_card": "",
      "right_next_card": "",
      "difficulté": "",
      "Kanji": "",
      "background": "#ccc",
      "image": "https://cdn-icons-png.flaticon.com/512/9190/9190361.png",
      "itemId": ""
    },
    {
      "Name": "kombini_start_4a",
      "id": "bc1fa208a5934b8e8086d14c98af21e8",
      "Unit": "092e7b31cd7a46a79a6d79f40d743a78",
      "Person": "g",
      "Status": "",
      "card_type": "",
      "character": "vendeur",
      "condition": {"irasshai_immunity2":true},
      "question": "Tu entres dans le kombini.\nLe vendeur essaie visiblement de communiquer avec toi.",
      "leftText": "Ignorer.",
      "onLeft": "",
      "rightText": "S’arrêter pour essayer de comprendre.",
      "onRight": "",
      "custom":{},
      "left_custom": {"irasshai_immunity":true, "irasshai_immunity_2":false},
      "right_custom": {"irasshai_immunity_2":false, "jumpscare":false},
      "left_next_card": "",
      "right_next_card": "",
      "difficulté": "",
      "Kanji": "",
      "background": "#ccc",
      "image": "https://cdn-icons-png.flaticon.com/512/9190/9190361.png",
      "itemId": ""
    },
    {
      "Name": "kombini_buy_easy",
      "id": "36a1fb3f88c94ad094fa150bcafed68f",
      "Unit": "092e7b31cd7a46a79a6d79f40d743a78",
      "Person": "g",
      "Status": "",
      "card_type": "multiple_answer_card",
      "character": "",
      "condition":{},
      "question": "Que voulez-vous acheter ?",
      "leftText": "",
      "onLeft": "",
      "rightText": "",
      "onRight": "",
      "custom":{},
      "left_custom": {},
      "right_custom": {},
      "left_next_card": "e2098d78628a49ad8c9a5d9cb04c8c87",
      "right_next_card": "e2098d78628a49ad8c9a5d9cb04c8c87",
      "difficulté": "",
      "Kanji": "viande (肉), poisson (魚)",
      "background": "#ccc",
      "image": "https://cdn-icons-png.flaticon.com/512/9190/9190361.png",
      "itemId": ""
    },
    {
      "Name": "kombini_end_1",
      "id": "e2098d78628a49ad8c9a5d9cb04c8c87",
      "Unit": "092e7b31cd7a46a79a6d79f40d743a78",
      "Person": "g",
      "Status": "",
      "card_type": "",
      "character": "vendeur",
      "condition":{},
      "question": "Tu t’apprêtes à sortir du kombini. Le vendeur te salue.\n”Maido.”",
      "leftText": "Presser le pas.",
      "onLeft": "",
      "rightText": "Ne rien répondre.",
      "onRight": "",
      "custom":{},
      "left_custom": {},
      "right_custom": {},
      "left_next_card": "",
      "right_next_card": "",
      "difficulté": "",
      "Kanji": "",
      "background": "#ccc",
      "image": "https://cdn-icons-png.flaticon.com/512/9190/9190361.png",
      "itemId": ""
    },
    {
      "Name": "meet_sweet_dog",
      "id": "0d0abc6b8f4a4d04b175a494d1a8bac9",
      "Unit": "023f6b2981ff4853826039b6e1845e62",
      "Person": "p",
      "Status": "",
      "card_type": "",
      "character": "",
      "condition":{},
      "question": "Un chien super mignon vient te voir !",
      "leftText": "Le caresser.",
      "onLeft": "+10B",
      "rightText": "L’ignorer et continuer son chemin.",
      "onRight": "",
      "custom":{},
      "left_custom": {},
      "right_custom": {},
      "left_next_card": "",
      "right_next_card": "",
      "difficulté": "",
      "Kanji": "",
      "background": "#ccc",
      "image": "https://cdn-icons-png.flaticon.com/512/8493/8493051.png",
      "itemId": ""
    },
    {
      "Name": "meet_mean_dog",
      "id": "bc2f87b9b56b4b06a21b021cd7816cc9",
      "Unit": "023f6b2981ff4853826039b6e1845e62",
      "Person": "p",
      "Status": "",
      "card_type": "",
      "character": "",
      "condition":{},
      "question": "Un chien débarque et t’aboies dessus ! Il menace de te mordre…",
      "leftText": "Essayer de l’apaiser.",
      "onLeft": "-20H",
      "rightText": "Fuir !",
      "onRight": "",
      "custom":{},
      "left_custom": {"bitten_dog":true},
      "right_custom": {},
      "left_next_card": "dca682768c1d4e4083f7cfb55cbb6bd4",
      "right_next_card": "",
      "difficulté": "",
      "Kanji": "",
      "background": "#ccc",
      "image": "https://cdn-icons-png.flaticon.com/512/3021/3021381.png",
      "itemId": ""
    },
    {
      "Name": "bitten_by_dog",
      "id": "dca682768c1d4e4083f7cfb55cbb6bd4",
      "Unit": "023f6b2981ff4853826039b6e1845e62",
      "Person": "p",
      "Status": "",
      "card_type": "",
      "character": "",
      "condition": {"bitten_dog":true},
      "question": "Le chien t’a mordu. Tu saignes.",
      "leftText": "Aïe.",
      "onLeft": "",
      "rightText": "Ouille.",
      "onRight": "",
      "custom":{},
      "left_custom": {},
      "right_custom": {},
      "left_next_card": "",
      "right_next_card": "",
      "difficulté": "",
      "Kanji": "",
      "background": "#ccc",
      "image": "https://cdn-icons-png.flaticon.com/512/3021/3021381.png",
      "itemId": ""
    },
    {
      "Name": "see_vending_machine_1",
      "id": "2c04e0b89dbe44ad84e4ee81cb62b237",
      "Unit": "023f6b2981ff4853826039b6e1845e62",
      "Person": "p",
      "Status": "",
      "card_type": "",
      "character": "",
      "condition":{},
      "question": "Oh ! Un distributeur !",
      "leftText": "Acheter quelque chose.",
      "onLeft": "",
      "rightText": "Continuer son chemin.",
      "onRight": "",
      "custom":{},
      "left_custom": {},
      "right_custom": {},
      "left_next_card": "",
      "right_next_card": "",
      "difficulté": "",
      "Kanji": "",
      "background": "#ccc",
      "image": "https://cdn-icons-png.flaticon.com/512/5348/5348463.png",
      "itemId": ""
    },
    {
      "Name": "see_vending_machine_2",
      "id": "10a6303a500a41a3a9d3544bd07fc630",
      "Unit": "023f6b2981ff4853826039b6e1845e62",
      "Person": "p",
      "Status": "",
      "card_type": "",
      "character": "",
      "condition":{},
      "question": "Tu trébuches… En te relevant, tu tombes nez à nez avec un distributeur.",
      "leftText": "Acheter quelque chose.",
      "onLeft": "",
      "rightText": "Continuer son chemin.",
      "onRight": "",
      "custom":{},
      "left_custom": {},
      "right_custom": {},
      "left_next_card": "",
      "right_next_card": "",
      "difficulté": "",
      "Kanji": "",
      "background": "#ccc",
      "image": "https://cdn-icons-png.flaticon.com/512/5348/5348463.png",
      "itemId": ""
    },
    {
      "Name": "see_vending_machine_3",
      "id": "839723f8edab4821bc7d8a21e0831c91",
      "Unit": "023f6b2981ff4853826039b6e1845e62",
      "Person": "p",
      "Status": "",
      "card_type": "",
      "character": "",
      "condition":{},
      "question": "Tu as cru entendre ton nom et te retourne. Derrière toi, un distributeur !",
      "leftText": "Acheter quelque chose.",
      "onLeft": "",
      "rightText": "Continuer son chemin.",
      "onRight": "",
      "custom":{},
      "left_custom": {},
      "right_custom": {},
      "left_next_card": "",
      "right_next_card": "",
      "difficulté": "",
      "Kanji": "",
      "background": "#ccc",
      "image": "https://cdn-icons-png.flaticon.com/512/5348/5348463.png",
      "itemId": ""
    },
    {
      "Name": "first_meet_with_crush",
      "id": "8b8beb3c472641e982e7ef798bd30625",
      "Unit": "023f6b2981ff4853826039b6e1845e62",
      "Person": "p",
      "Status": "",
      "card_type": "",
      "character": "",
      "condition": {"meet_crush":false},
      "question": "Quelqu’un te bouscule et renverse ton café. Tu es énervé.e, mais tu vois le plus bel.le homme/femme que tu n’as jamais vu.",
      "leftText": "T’excuser.",
      "onLeft": "",
      "rightText": "T’énerver quand même et partir.",
      "onRight": "",
      "custom":{},
      "left_custom": {"meet_crush":true},
      "right_custom": {},
      "left_next_card": "",
      "right_next_card": "",
      "difficulté": "",
      "Kanji": "",
      "background": "#ccc",
      "image": "https://cdn-icons-png.flaticon.com/512/1993/1993167.png",
      "itemId": ""
    },
    {
      "Name": "see_laundry",
      "id": "da085f7dd63a46219d1943098e87819a",
      "Unit": "023f6b2981ff4853826039b6e1845e62",
      "Person": "p",
      "Status": "",
      "card_type": "",
      "character": "",
      "condition":{},
      "question": "Ah, une laverie ! Tu sauras où laver ton linge la prochaine fois.",
      "leftText": "Ok.",
      "onLeft": "",
      "rightText": "D’acc.",
      "onRight": "",
      "custom":{"laundry":true},
      "left_custom": {},
      "right_custom": {},
      "left_next_card": "",
      "right_next_card": "",
      "difficulté": "",
      "Kanji": "",
      "background": "#ccc",
      "image": "https://cdn-icons-png.flaticon.com/512/4357/4357116.png",
      "itemId": ""
    },
    {
      "Name": "see_restaurant",
      "id": "6c2c6c2cbd9b43f58f49f7073b91cdc4",
      "Unit": "023f6b2981ff4853826039b6e1845e62",
      "Person": "p",
      "Status": "",
      "card_type": "",
      "character": "",
      "condition":{},
      "question": "Ce restaurant donne faim ! Il faudra y faire un tour la prochaine fois !",
      "leftText": "Non, je veux manger maintenant !",
      "onLeft": "-20A, +20B, +5H",
      "rightText": "Il faudra que j’y invite quelqu’un.",
      "onRight": "",
      "custom":{},
      "left_custom": {},
      "right_custom": {},
      "left_next_card": "",
      "right_next_card": "",
      "difficulté": "",
      "Kanji": "",
      "background": "#ccc",
      "image": "https://cdn-icons-png.flaticon.com/512/3361/3361903.png",
      "itemId": ""
    },
    {
      "Name": "find_money_on_floor",
      "id": "8910581c2df84e79b0a06574c2e25f28",
      "Unit": "023f6b2981ff4853826039b6e1845e62",
      "Person": "p",
      "Status": "",
      "card_type": "",
      "character": "",
      "condition":{},
      "question": "Quelle chance ! Un billet de 5000 yens par terre !",
      "leftText": "Les prendre.",
      "onLeft": "+20A",
      "rightText": "Les donner à un sans-abri.",
      "onRight": "+20B",
      "custom":{},
      "left_custom": {},
      "right_custom": {},
      "left_next_card": "",
      "right_next_card": "",
      "difficulté": "",
      "Kanji": "",
      "background": "#ccc",
      "image": "https://cdn-icons-png.flaticon.com/512/7630/7630510.png",
      "itemId": ""
    },
    {
      "Name": "thief_street",
      "id": "04bd164197c04d4a8a8fb3c51a31f861",
      "Unit": "023f6b2981ff4853826039b6e1845e62",
      "Person": "p",
      "Status": "",
      "card_type": "",
      "character": "",
      "condition":{},
      "question": "Un homme sympathique vient te voir et te dit de regarder derrière toi.",
      "leftText": "L’ignorer et continuer ton chemin.",
      "onLeft": "",
      "rightText": "Regarder.",
      "onRight": "",
      "custom":{},
      "left_custom": {},
      "right_custom": {},
      "left_next_card": "",
      "right_next_card": "6bafa0fdf65d41b78111396371a0ea51",
      "difficulté": "",
      "Kanji": "",
      "background": "#ccc",
      "image": "https://cdn-icons-png.flaticon.com/512/4352/4352392.png",
      "itemId": ""
    },
    {
      "Name": "money_stolen",
      "id": "6bafa0fdf65d41b78111396371a0ea51",
      "Unit": "023f6b2981ff4853826039b6e1845e62",
      "Person": "p",
      "Status": "",
      "card_type": "",
      "character": "",
      "condition":{},
      "question": "L’homme t’a volé tout l’argent que tu avais sur toi !!!",
      "leftText": "Rentrer chez soi.",
      "onLeft": "-10B, -30A",
      "rightText": "Crier “Au voleur !”",
      "onRight": "-10B, -30A",
      "custom":{},
      "left_custom": {},
      "right_custom": {},
      "left_next_card": "",
      "right_next_card": "",
      "difficulté": "",
      "Kanji": "",
      "background": "#ccc",
      "image": "https://cdn-icons-png.flaticon.com/512/7274/7274005.png",
      "itemId": ""
    },
  ];

  

  const getCardByIndex = (index) => {
    return Cards[index % Cards.length];
  };

  const getCardById = (id) => {
    return Cards.filter(function(Card) {return (Card.id == id);})[0];
  };

  return {
    Cards,
    getCardByIndex,
    getCardById,
  };
}
